import path from 'path';
import swaggerJSDoc from 'swagger-jsdoc';

/**
 * Swagger definition.
 */
const swaggerDefinition = {
  info: {
    title: 'Mome Application Using Express and MySQL',
    version: '1.0.0',
    description: 'RESTful API description with Swagger',
  },
  basePath: '/api',
  securityDefinitions: {
    Bearer: {
      description:'For accessing the API a valid JWT token must be passed in all the queries in the \'Authorization\' header.' +'\n\n'+
        'A valid JWT token is generated by the API and returned as answer of a call to the route \'/auths/login\' giving a valid email & password. '+'\n\n\n'+
        'The following syntax must be used in the \'Authorization\' header:' +'\n\n'+
        'Bearer xxxxxx.yyyyyyy.zzzzzz',
      type: 'apiKey',
      name: 'Authorization',
      in: 'header',
    },
  },
};

/**
 * Options for the swagger docs.
 */
const swaggerOptions = {
  // import swaggerDefinitions
  swaggerDefinition: swaggerDefinition,
  // path to the API docs
  apis: [path.join(__dirname, '/../routes/*.js')],
};

/**
 * Initialize swagger-jsdoc.
 */
const swagger = swaggerJSDoc(swaggerOptions);

export default swagger;